### ISSUE TITLE
Stacktraces when killing villagers

### ISSUE THREAD

**Issue by SERISET** [teakivy/teaks-tweaks#48]
I updated to 1.20.1 and have the latest version of Teak's Tweaks. I wanted to cleanup my plugins so I removed TeakTweaks and the config folder and reinstalled it, and reapplied my settings manually.

Today I got a few stacktaces when a player killed villagers.

```
[17:10:13] [Server thread/INFO]: Villager EntityVillager['Shepherd'/106779, uuid='8f21018c-dd63-4292-b558-c8495a3f5c71', l='ServerLevel[world]', x=-3482.70, y=63.00, z=15790.70, cpos=[-218, 986], tl=1302, v=true] died, message: 'Shepherd was slain by hippopo2000'
[17:10:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to TeaksTweaks v1.10.0-beta
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager cannot be cast to class org.bukkit.entity.ZombieVillager (org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager and org.bukkit.entity.ZombieVillager are in unnamed module of loader java.net.URLClassLoader @421faab1)
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.mobs.ZombieVillagerHead.getName(ZombieVillagerHead.java:63) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.getHead(BaseMobHead.java:68) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.onDeath(BaseMobHead.java:60) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-30]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-30]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-30]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:897) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1811) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1705) ~[?:?]
	at net.minecraft.world.entity.npc.AbstractVillager.die(AbstractVillager.java:229) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.die(Villager.java:695) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1529) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1320) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2874) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2798) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-30]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:14:36] [Server thread/INFO]: Villager EntityVillager['Butcher'/111911, uuid='cb7c142a-778e-4e54-94d5-86c6ad57faf1', l='ServerLevel[world]', x=-2403.48, y=65.00, z=17231.14, cpos=[-151, 1076], tl=2377, v=true] died, message: 'Butcher was slain by hippopo2000'
[17:14:36] [Server thread/ERROR]: Could not pass event EntityDeathEvent to TeaksTweaks v1.10.0-beta
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager cannot be cast to class org.bukkit.entity.ZombieVillager (org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager and org.bukkit.entity.ZombieVillager are in unnamed module of loader java.net.URLClassLoader @421faab1)
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.mobs.ZombieVillagerHead.getName(ZombieVillagerHead.java:63) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.getHead(BaseMobHead.java:68) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.onDeath(BaseMobHead.java:60) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-30]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-30]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-30]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:897) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1811) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1705) ~[?:?]
	at net.minecraft.world.entity.npc.AbstractVillager.die(AbstractVillager.java:229) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.die(Villager.java:695) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1529) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1320) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2874) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2798) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-30]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:15:07] [Server thread/INFO]: Villager EntityVillager['Cartographer'/111783, uuid='66215850-7dbe-448b-9f19-8bb0d52d5f92', l='ServerLevel[world]', x=-2400.51, y=64.00, z=17225.19, cpos=[-151, 1076], tl=3006, v=true] died, message: 'Cartographer was slain by hippopo2000'
[17:15:07] [Server thread/ERROR]: Could not pass event EntityDeathEvent to TeaksTweaks v1.10.0-beta
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager cannot be cast to class org.bukkit.entity.ZombieVillager (org.bukkit.craftbukkit.v1_20_R1.entity.CraftVillager and org.bukkit.entity.ZombieVillager are in unnamed module of loader java.net.URLClassLoader @421faab1)
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.mobs.ZombieVillagerHead.getName(ZombieVillagerHead.java:63) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.getHead(BaseMobHead.java:68) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at me.teakivy.teakstweaks.packs.mobs.moremobheads.BaseMobHead.onDeath(BaseMobHead.java:60) ~[TeaksTweaks.-.1.10.0-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-30]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-30]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-30]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:897) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1811) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1705) ~[?:?]
	at net.minecraft.world.entity.npc.AbstractVillager.die(AbstractVillager.java:229) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.die(Villager.java:695) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1529) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1320) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2874) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2798) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-30]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-30]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by teakivy** [comment]
Will be fixed in v1.10.1-beta
