### ISSUE TITLE
None of the Tweaks are Woking

### ISSUE THREAD

**Issue by CptGummiball** [teakivy/teaks-tweaks#88]
**Describe the bug**
Got Error while enabling the Plugin.
Spigot 1.20.4
TeaksTweaks 1.10.6-beta

**To Reproduce**
1. Enable some Features in config.yml
2. Start the Server

**Expected behavior**
Tweaks working

**Screenshots**

**Additional context**
Error Log:
[11:09:43] [Server thread/ERROR]: Error occurred while enabling TeaksTweaks v1.10.6-beta (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.ItemStack.setLore(java.util.List)'
at me.teakivy.teakstweaks.craftingtweaks.AbstractRecipe.init(AbstractRecipe.java:60) ~[?:?]
at me.teakivy.teakstweaks.craftingtweaks.AbstractRecipe.register(AbstractRecipe.java:68) ~[?:?]
at me.teakivy.teakstweaks.craftingtweaks.CraftingRegister.registerAll(CraftingRegister.java:52) ~[?:?]
at me.teakivy.teakstweaks.Main.onEnable(Main.java:63) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by teakivy** [comment]
As of recent versions, Teaks Tweaks no longer fully supports spigot, please use paper or any subsequent fork of paper

https://papermc.io/downloads/paper
