### ISSUE TITLE
config.yml parsing / config broke

### ISSUE THREAD

**Issue by pokameni** [teakivy/teaks-tweaks#89]
Hello. I can't use Teaks Tweaks.

**Describe the bug**
The `config.yml` breaks after some editing.

**Versions**
- Teaks Tweaks v1.10.6-beta
- PaperMC git-Paper-446 (MC: 1.20.4)

**Installed Plugins**
- GriefPrevention, GroupManager, SetHomes, SimpleTpa, SkinsRestorer, TeaksTweaks, Tweakin, Vault

**To Reproduce**
- Installed Teaks Tweaks v1.10.6-beta
- Restarted 
- Did some /tweaks enable packs
- at this point i did checked up the config, and it wasn't like the actual one, fully packed/condensed
- Restarted again
- Did some editing into `config.yml` due to crafting packs can't be enabled as of commands
- Restarted again
- the config DID resets by himself and plugin did some errors.
- my config gone, F and poggers in chat.

**Expected behavior**
- the confing should NOT resets by himself and the parse should pass correctly.

**Additional context**
- i used before Tweakin' and Teak Tweaks together, like in 1.14.4, in the exact same environnement, i did never gave up my hosting provider.
- also hading a config.yml.broke or anything like that feature in the plugin could be nice. :(

***Logs**
```js
[00:07:40] [Server thread/INFO]: [TeaksTweaks] Enabling TeaksTweaks v1.10.6-beta
[00:07:40] [Server thread/ERROR]: Cannot load plugins/TeaksTweaks/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 41, column 3:
      keep-small:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 62, column 5:
        enabled: false
        ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:179) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at me.teakivy.teakstweaks.Main.onEnable(Main.java:39) ~[TeaksTweaks.-.1.10.6-beta.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-446]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 41, column 3:
      keep-small:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 62, column 5:
        enabled: false
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:330) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 18 more
[00:07:40] [Server thread/ERROR]: Cannot load plugins/TeaksTweaks/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 41, column 3:
      keep-small:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 62, column 5:
        enabled: false
        ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at me.teakivy.teakstweaks.utils.ConfigUpdater.update(ConfigUpdater.java:42) ~[TeaksTweaks.-.1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.Main.updateConfig(Main.java:148) ~[TeaksTweaks.-.1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.Main.onEnable(Main.java:53) ~[TeaksTweaks.-.1.10.6-beta.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-446]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 41, column 3:
      keep-small:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 62, column 5:
        enabled: false
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:330) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 18 more
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] Updated Config to Version: 50
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] Registered Command: /teakstweaks
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] Registered Command: /mechanics
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] Registered Command: /packlist
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] 
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] Teak's Tweaks Started!
[00:07:40] [Server thread/INFO]: [TeaksTweaks] [INFO] 
```

**Comment by teakivy** [comment]
/teakstweaks enable/disable only enables packs temporarily (until the server restarts). This feature was meant for testing, and subsequently will be removed in the next version.

As for the error specified, it appears you provided an invalid yml format that it was unable to read. Please be sure to check formatting and follow yml conventions https://www.yamllint.com/
