### ISSUE TITLE
graves error out / do not completely save an inventory

### ISSUE THREAD

**Issue by SubnovaJH** [teakivy/teaks-tweaks#90]
**Describe the bug**
Randomly, whenever a player dies on my server, their inventory is not sent to a grave and instead an error gets sent to the console while their items drop to the ground like vanilla Minecraft without keepInventory enabled. I am unable to reproduce it with confidence, and know only that it happens to a few players on my server randomly.

**Expected behavior**
When a player dies, their inventory should go into a grave.

**Screenshots**
```
[22:17:40] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to TeaksTweaks v1.10.6-beta
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
	at me.teakivy.teakstweaks.packs.survival.graves.GraveCreator.getSkullTexture(GraveCreator.java:244) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.packs.survival.graves.GraveCreator.serializeItems(GraveCreator.java:202) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.packs.survival.graves.GraveCreator.createGrave(GraveCreator.java:82) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.packs.survival.graves.GraveEvents.onDeath(GraveEvents.java:155) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1019) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:968) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1565) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:970) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
	at net.minecraft.world.level.Explosion.explode(Explosion.java:597) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.world.level.Level.explode(Level.java:1406) ~[?:?]
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1939) ~[?:?]
	at net.minecraft.world.level.Level.explode(Level.java:1365) ~[?:?]
	at net.minecraft.world.entity.monster.Creeper.explodeCreeper(Creeper.java:276) ~[?:?]
	at net.minecraft.world.entity.monster.Creeper.tick(Creeper.java:163) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1409) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1318) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:916) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:896) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:17:40] [Server thread/INFO]: ****** was blown up by Creeper
```

**Additional context**
We are running Minecraft 1.20.4 via Paper, using stable build #496. We are using the following plugins:

- BlockProt
- Chunky
- DiscordSRV
- FreedomChat
- LoginSecurity
- Lootin
- PL-Hide
- ProtocolLib
- SimplePermissionConfigurator
- SkinsRestorer
- spark
- TeaksTweaks

We have the following tweaks enabled from your plugin:

- Sudoku
- Stair Chairs
- Unsticky Pistons
- Dirt to Grass
- AFK Display
- Graves
- Player Head Drops
- Anti Enderman Grief
- Bat Membranes
- Spawn
- Universal Dyeing
- Craftable Bundles Rabbit Hide

**Comment by teakivy** [comment]
This has been resolved in v1.11.0-beta :)
