### ISSUE TITLE
Spawn command not working in version 1.10.6-beta = Unhandled exception executing 'spawn'

### ISSUE THREAD

**Issue by Xavom** [teakivy/teaks-tweaks#91]
**Describe the bug**
Cannot get the spawn command to work with throwing an error. 
Testing on a paper-1.20.4-497 server with no other plugins.

**To Reproduce**
1. Create a new paper-1.20.4-497 server.
2. Download TeaksTweaks - 1.10.6-beta.jar into the plugins folder.
3. Start the server to create the config files, once loaded shut it down.
4. Edit the config.yml file to enable /spawn command.
5. Start the server and join.
6. Issue the command /spawn and watch the console output.

**Expected behavior**
Spawn command teleports the player to world spawn.

**Screenshots**
none

**Additional context**
A partial dump of the console:

```
[15:48:14 INFO]: [TeaksTweaks] Enabling TeaksTweaks v1.10.6-beta
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /teakstweaks
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /mechanics
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /spawn
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /tpa
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /home
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /back
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /afk
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /sethome
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /packlist
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Command: /delhome
[15:48:14 INFO]: [TeaksTweaks] [INFO] 
[15:48:14 INFO]: [TeaksTweaks] [INFO] Teak's Tweaks Started!
[15:48:14 INFO]: [TeaksTweaks] [INFO] 
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: Unlock All Recipes
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: AFK Display
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: Silence Mobs
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: Spawn
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: Homes
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: TPA
[15:48:14 INFO]: [TeaksTweaks] [INFO] Registered Pack: Back
[15:48:14 INFO]: Running delayed init tasks
[15:48:14 INFO]: Done (1.813s)! For help, type "help"
[15:48:14 INFO]: Timings Reset
[15:49:08 INFO]: UUID of player Xavom is f64ec575-a297-4b49-85c2-846fef73f701
[15:49:08 INFO]: Xavom joined the game
[15:49:08 INFO]: Xavom[/127.0.0.1:45436] logged in with entity id 321 at ([temp1.20.4_the_end]9.40592756093903, 64.20199120685473, -5.838312939765493)
[15:49:21 INFO]: Xavom issued server command: /gamemode creative
[15:49:21 INFO]: [Xavom: Set own game mode to Creative Mode]
[15:49:39 INFO]: Xavom issued server command: /setworldspawn
[15:49:39 INFO]: [Xavom: Set the world spawn point to 8, 72, -8 [0.0]]
[15:49:44 INFO]: Xavom issued server command: /spawn
[15:49:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'spawn' in me.teakivy.teakstweaks.utils.AbstractCommand$ReflectCommand(spawn)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-497]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getSpawnLocation()" because "world" is null
	at me.teakivy.teakstweaks.commands.SpawnCommand.teleportToSpawn(SpawnCommand.java:77) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.commands.SpawnCommand.onCommand(SpawnCommand.java:58) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at me.teakivy.teakstweaks.utils.AbstractCommand$ReflectCommand.execute(AbstractCommand.java:101) ~[TeaksTweaks - 1.10.6-beta.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
```

**Comment by teakivy** [comment]
This has been resolved in v1.11.0-beta :)
